### PR TITLE
Update steamworks library for Valheim 0.217.28

### LINKED ISSUE #19: Crash on startup since Valheim 0.217.28 (Nov 7 update)
Stacktrace from dedicated server (only mod installed is Better Networking).
```
11/09/2023 10:38:17: Using default prefs
11/09/2023 10:38:17: Console: Valheim 0.217.29 (network version 17)
11/09/2023 10:38:17: Console:
11/09/2023 10:38:17: Console: type "help" - for commands
11/09/2023 10:38:17: Console:
11/09/2023 10:38:17: isModded: False
11/09/2023 10:38:17: Zonesystem Awake 363004
11/09/2023 10:38:17: DungeonDB Awake 363004
11/09/2023 10:38:17: Registering lobby

=================================================================
        Native Crash Reporting
=================================================================
Got a UNKNOWN while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

=================================================================
        Managed Stacktrace:
=================================================================
          at <unknown> <0xffffffff>
          at Steamworks.NativeMethods:ISteamNetworkingUtils_SetConfigValue <0x000b4>
          at Steamworks.SteamGameServerNetworkingUtils:DMD<Steamworks.SteamGameServerNetworkingUtils::SetConfigValue> <0x00092>
          at NetworkSendRate_Patch:SetSteamNetworkConfig <0x002a2>
          at NetworkSendRate_Patch:SetSendRateMinFromConfig <0x00032>
          at PreventValheimControlOfNetworkRate_Patch:Prefix <0x0001a>
          at ZSteamSocket:DMD<ZSteamSocket::RegisterGlobalCallbacks> <0x00032>
          at ZSteamSocket:.ctor <0x0024a>
          at ZNet:Awake <0x0069a>
          at System.Object:runtime_invoke_void__this__ <0x00087>
=================================================================

========== OUTPUTTING STACK TRACE ==================

0x00007FF8021074AC (steamclient64) Breakpad_SteamWriteMiniDumpUsingExceptionInfoWithBuildId
0x00007FF80210210C (steamclient64) Breakpad_SteamWriteMiniDumpUsingExceptionInfoWithBuildId
0x000002311765A145 (Mono JIT Code) (wrapper managed-to-native) Steamworks.NativeMethods:ISteamNetworkingUtils_SetConfigValue (intptr,Steamworks.ESteamNetworkingConfigValue,Steamworks.ESteamNetworkingConfigScope,intptr,Steamworks.ESteamNetworkingConfigDataType,intptr)
0x0000023021E9D303 (Mono JIT Code) (wrapper dynamic-method) Steamworks.SteamGameServerNetworkingUtils:DMD<Steamworks.SteamGameServerNetworkingUtils::SetConfigValue> (Steamworks.ESteamNetworkingConfigValue,Steamworks.ESteamNetworkingConfigScope,intptr,Steamworks.ESteamNetworkingConfigDataType,intptr)
0x0000023117656733 (Mono JIT Code) CW_Jesse.BetterNetworking.BN_Patch_SendRate/NetworkSendRate_Patch:SetSteamNetworkConfig (Steamworks.ESteamNetworkingConfigValue,int)
0x0000023117656473 (Mono JIT Code) CW_Jesse.BetterNetworking.BN_Patch_SendRate/NetworkSendRate_Patch:SetSendRateMinFromConfig ()
0x00000231176563BB (Mono JIT Code) CW_Jesse.BetterNetworking.BN_Patch_SendRate/PreventValheimControlOfNetworkRate_Patch:Postfix ()
0x0000023021E9D97B (Mono JIT Code) (wrapper dynamic-method) ZSteamSocket:DMD<ZSteamSocket::RegisterGlobalCallbacks> ()
0x00000231176557DB (Mono JIT Code) ZSteamSocket:.ctor ()
0x000002311764F74B (Mono JIT Code) ZNet:Awake ()
0x00000230C86976A8 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
0x00007FF811004B6E (mono-2.0-bdwgc) mono_jit_set_domain
0x00007FF810F3D204 (mono-2.0-bdwgc) mono_object_get_virtual_method
0x00007FF810F3D37C (mono-2.0-bdwgc) mono_runtime_invoke
```

### PR DESCRIPTION
**Pull request by jsza**
Fixes #19

### CODE REVIEW

**Comment by CW-Jesse** [comment]
I'll take a look at this as soon as I can.

**Review by CW-Jesse — APPROVED** [review]

**Review by CW-Jesse — APPROVED** [review]

**Review by CW-Jesse — APPROVED** [review]

**Comment by CW-Jesse** [comment]
@jsza It's published, mod is back online, no new complaints, and attribution to you is given on Thunderstore and NexusMods.

Let me know if anything else is needed!

**Comment by jsza** [comment]
@CW-Jesse Cool, thanks for merging my PR and glad things seem to have worked out! 

Went down a bit of a rabbit hole with this one trying to figure out why the same engine calls weren’t crashing until doing something unrelated with a publicised `assembly_valheim` caused VS to complain about a missing type from the newly named Steamworks DLL. Well, hope it can be useful for next time something like this happens. It was doubly confusing because `assembly_steamworks` still exists, it just doesn’t seem to be used.

Also thanks for the plugin, really cool stuff and it’s been super helpful!

**Comment by CW-Jesse** [comment]
@jsza Thank you! I'm glad it's been helpful for you, and I'm grateful for your contribution back.

I think the biggest clue was in the patch notes where they mentioned "Steamworks **.NET**" which made my eyebrow go up. I wonder if they kept the old version in there by mistake or for mod compatibility. They updated the Unity major version, so mod compatibility wasn't their highest priority.

**Pull request merged**
